### PR TITLE
fix CreateStream without shardCount

### LINKED ISSUE #336: [BUG] create-stream without shard-count fails with SerializationException
**Describe the bug**
The `CreateStreamRequest` defines the `shardCount` as mandatory / not optional.
This results in serialization errors when invoking `create-stream` if the `shard-count` is not set.

A request against AWS without the `shardCount` works:
```
aws kinesis create-stream --stream-name test
```
It's also marked as optional in the AWS CLI docs on `create-stream`: https://docs.aws.amazon.com/cli/latest/reference/kinesis/create-stream.html

**To Reproduce**
```
$ docker pull ghcr.io/etspaceman/kinesis-mock:0.2.4
$ docker run -d -p 4568:4568 ghcr.io/etspaceman/kinesis-mock:0.2.4
$ aws --endpoint-url=http://localhost:4568 kinesis create-stream --stream-name test

An error occurred (SerializationException) when calling the CreateStream operation: Invalid message body: Could not decode JSON: {
  "StreamName" : "test"
}
```

**Expected behavior**
The `shardCount` should be optional, i.e. the following request should successfully create a stream:
```
aws --endpoint-url=http://localhost:4568 kinesis create-stream --stream-name test
```

**Additional context**
Thanks for the great tool! Please let me know if any more info would be helpful.
I could also try to file a PR if the issue is confirmed. 🙂

### PR DESCRIPTION
**Pull request by alexrashed**
## Changes Introduced
Make the `shardCount` in the `CreateStreamRequest` optional (default to 4).

## Applicable linked issues
Fixes #336.

## Checklist (check all that apply)

- [x] This change maintains backwards compatibility
- [x] I have introduced tests for all new features and changes
- [x] I have added documentation covering all new features and changes
- [x] This pull-request is ready for review

### CODE REVIEW

File: src/main/scala/kinesis/mock/api/CreateStreamRequest.scala [hunk 1]
```diff
@@ -10,7 +10,7 @@ import kinesis.mock.models._
 import kinesis.mock.syntax.either._
 import kinesis.mock.validations.CommonValidations
 
-final case class CreateStreamRequest(shardCount: Int, streamName: StreamName) {
+final case class CreateStreamRequest(streamName: StreamName, shardCount: Int = 4) {
```
Comment (etspaceman) [inline src/main/scala/kinesis/mock/api/CreateStreamRequest.scala:13]: This should be an `Option[Int]`, with the logic below providing `4` when the value is not provided. These classes should represent the requests the best that they can. Really not a fan of the default parameter.

File: src/main/scala/kinesis/mock/cache/CacheConfig.scala [hunk 2]
```diff
@@ -112,16 +112,15 @@ object CacheConfig {
       .traverse {
         case name :: count :: Nil if name.nonEmpty && count.nonEmpty =>
```
Comment (etspaceman) [inline src/main/scala/kinesis/mock/cache/CacheConfig.scala:113]: You'll need to change this so that the `count.nonEmpty` check is not enforced.

File: src/main/scala/kinesis/mock/cache/CacheConfig.scala [hunk 3]
```diff
@@ -112,16 +112,15 @@ object CacheConfig {
...
           count.toIntOption.map(x =>
-            defaultRegion -> CreateStreamRequest(x, StreamName(name))
+            defaultRegion -> CreateStreamRequest(StreamName(name), x)
           )
         case name :: count :: region :: Nil
             if name.nonEmpty && count.nonEmpty =>
```
Comment (etspaceman) [inline src/main/scala/kinesis/mock/cache/CacheConfig.scala:118]: [Ditto](https://github.com/etspaceman/kinesis-mock/pull/339/files#r932234869)

File: src/main/scala/kinesis/mock/api/CreateStreamRequest.scala [hunk 4]
```diff
@@ -10,14 +10,15 @@ import kinesis.mock.models._
...
-final case class CreateStreamRequest(shardCount: Int, streamName: StreamName) {
+final case class CreateStreamRequest(shardCount: Option[Int], streamName: StreamName) {
   def createStream(
       streamsRef: Ref[IO, Streams],
       shardLimit: Int,
       awsRegion: AwsRegion,
       awsAccountId: AwsAccountId
   ): IO[Response[Unit]] =
     streamsRef.modify { streams =>
+      val shardCountOrDefault = shardCount.getOrElse(4)
```
Comment (etspaceman) [inline src/main/scala/kinesis/mock/api/CreateStreamRequest.scala:21]: 👍

File: src/test/scala/kinesis/mock/cache/CacheConfigTests.scala [hunk 5]
```diff
@@ -139,15 +139,8 @@ class CacheConfigTests
         val res = List(
           CacheConfig
             .initializeStreamsReader(awsRegion, s":$streamName1"),
-          CacheConfig
-            .initializeStreamsReader(awsRegion, s"$streamName1:"),
           CacheConfig
             .initializeStreamsReader(awsRegion, s",$streamName1:3"),
-          CacheConfig
```
Comment (etspaceman) [inline src/test/scala/kinesis/mock/cache/CacheConfigTests.scala:146]: Can you add a test that asserts that providing no shard count works properly?

File: src/test/scala/kinesis/mock/instances/arbitrary.scala [hunk 6]
```diff
@@ -250,13 +250,14 @@ object arbitrary {
     } yield AddTagsToStreamRequest(streamName, tags)
   )
 
-  implicit val createStreamRequestArb: Arbitrary[CreateStreamRequest] =
+  implicit val createStreamRequestArb: Arbitrary[CreateStreamRequest] = {
     Arbitrary(
       for {
-        shardCount <- Gen.choose(1, 1000)
+        shardCount: Option[Int] <- Gen.option(Gen.choose(1, 1000))
```
Comment (etspaceman) [inline src/test/scala/kinesis/mock/instances/arbitrary.scala:256]:
```suggestion
        shardCount <- Gen.option(Gen.choose(1, 1000))
```

File: src/test/scala/kinesis/mock/cache/CacheConfigTests.scala (hunk 5 above)
Comment (alexrashed) [reply src/test/scala/kinesis/mock/cache/CacheConfigTests.scala:146]: Good point, thanks!
I added the tests in the latest commit (there was actually still a bug when no shardCount was given at all).

File: src/main/scala/kinesis/mock/cache/CacheConfig.scala (hunk 2 above)
Comment (alexrashed) [reply src/main/scala/kinesis/mock/cache/CacheConfig.scala]: Thanks for the hint! Totally overlooked the `INITIALIZE_STREAMS` feature (I was mostly relying on the type system / fixing type issues). I also adjusted the README in the last commit.

**Comment by etspaceman** [comment]
Thanks for the contribution!!

**Comment by alexrashed** [comment]
Thanks for the patience and guidance (first time scala contribution)! :)
